Add Strikes to account KP command
Maselkov/GW2Bot pull request #98
Opened 2020-08-23 22:06 UTC by ShiningMassXAcc

Add strikes to game data
Add support for progression checking of single achievement

2020-08-23 22:07 UTC, ShiningMassXAcc commented
Similar question from other PRs - I've not actually done anything with discord bots or python before.  I have not run this, and could use a bit of direction to test or validate (unless, since this is small - you want to run with it).

2020-08-24 10:26 UTC, Maselkov requested changes
You can find instructions on how to test [here](https://github.com/Maselkov/GW2Bot/pull/89#issuecomment-569926230). I really need to update the readme

Also need to change the line 200 to support `progressed_achievement` type

2020-08-24 10:26 UTC, Maselkov commented on guildwars2/account.py
> +                    if achievement["id"] == _id and achievement["current"] >= _progress
Syntax error

2020-08-25 01:54 UTC, ShiningMassXAcc commented on guildwars2/account.py
> +                    if achievement["id"] == _id and achievement["current"] >= _progress
Done

2020-08-25 01:57 UTC, ShiningMassXAcc commented
> You can find instructions on how to test [here](https://github.com/Maselkov/GW2Bot/pull/89#issuecomment-569926230). I really need to update the readme
> 
> Also need to change the line 200 to support `progressed_achievement` type

Test instructions helped.  Here's two screenshots from my account (that is noob) and another count that is full clear.

![image](https://user-images.githubusercontent.com/43765765/91113962-a130a480-e63b-11ea-8c95-9aea85afed68.png)

![image](https://user-images.githubusercontent.com/43765765/91113885-721a3300-e63b-11ea-8159-a006f7c77806.png)

2020-08-26 17:42 UTC, Maselkov approved these changes
Thank you!

2020-08-26 17:42 UTC, merged